package com.endava.demo.mapper;

import com.endava.demo.dto.UserDto;
import com.endava.demo.entity.User;
import org.mapstruct.Mapper;

/**
 * The implementation class is autogenerated with Mapstruct, so it can be found on the following location:
 * /target/generated-sources/annotations/com/endava/demo/mapper/UserMapperImpl.class
 */

@Mapper(componentModel = "spring")
public interface UserMapper {

    /**
     * Entity to Dto.
     * The method populate every field in the Dto object with the same name field in the Entity.
     *
     * @param user Entity object with information for database population
     * @return     Dto object with the certain information
     */
    UserDto toDto(User user);

    /**
     * Dto to Entity.
     * The method populate every field in the Entity object with the same name field in the Dto.
     *
     * @param userDto Dto object with view information
     * @return        Entity object with certain information, but not less than what is required from database
     */
    User toEntity(UserDto userDto);

}
